name: Test, dockerize and deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test:
    name: Test - Unit
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Maven Package
        run: mvn -B clean package

  docker:
    name: build image and publish
    runs-on: ubuntu-18.04
    needs: [test]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }}
          -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker image
        run: docker build -t wherbawi/spring-app:latest .
      - name: Publish Docker image
        run: docker push wherbawi/spring-app

  redeploy:
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - name: ssh connect and run container
        uses: fifsky/ssh-action@master
        with: 
         command: |
          docker pull wherbawi/spring-app:latest
          docker stop SpringApp
          docker system prune -f
          docker run -d -p 8080:8080 --name SpringApp wherbawi/spring-app:latest
         host: ${{ secrets.STAGING_SERVER_IP }}
         user: ${{ secrets.STAGING_SERVER_DEPLOY_USR }}
         key: ${{ secrets.STAGING_SERVER_KEY }}
